### PR TITLE
feat: implement staff page and necessary components

### LINKED ISSUE #17: Staff page and Components
Create the components for use in the staff page, and set up basic layout for the page

### PR DESCRIPTION
**Pull request by JDinis88**
## Changes
1. Created Staff Card component and Staff data type
2. Created Staff page
3. Created dummy data for staff cards
4. Added basic css to match overall scheme

## Purpose
Implement a necessary page, and make it easy for quick additions or changes

Closes #017

### CODE REVIEW

**Review by tkgonzal — APPROVED** [review]
(praise): Looks good ! Please add the scope part (the subject in parentheses) to your pr's title :^)

**Comment by JDinis88** [comment]
> (praise): Looks good ! Please add the scope part (the subject in parentheses) to your pr's title :^)

Left out intentionally, because the scope is broad and involves many different parts, in accordance with the convention

**Comment by tkgonzal** [comment]
thought: Mm for sure. I assumed most of the stuff in the pr would've fallen under the staff-page as a topic, but I trust your judgement on it !

**Review by IvanPiceno171 — APPROVED** [review]
(praise): Looks good

**Pull request merged**
